

import type { Product } from './types';

export const allProducts: Product[] = [
    // --- MEN'S PRODUCTS (NEW) ---
    {
        id: 42490,
        name: "Eau de Parfum Ascendant Intense",
        brand: "Ascendant",
        price: 34.99,
        regularPrice: 52.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42490%2F42490_1.png&MediaId=19190183&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Una fragancia intensa y poderosa para el hombre moderno. Notas orientales y especiadas de Cardamomo y Guaraná que dejan una huella imborrable.",
        stock: 45,
        category: 'men',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 120
    },
    {
        id: 35878,
        name: "Limpiadora y Exfoliante de Carbón Activo North For Men",
        brand: "North For Men",
        price: 9.99,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35878%2F35878_1.png&MediaId=19190183&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Gel limpiador facial profundo con Carbón Activo. Elimina impurezas, exceso de grasa y suciedad de la contaminación. Deja la piel fresca y energizada.",
        stock: 80,
        category: 'men',
        rating: 4.7,
        reviewCount: 95
    },
    {
        id: 29446,
        name: "Set Experto Novage Men",
        brand: "Novage Men",
        price: 89.99,
        regularPrice: 139.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F29446%2F29446_1.png&MediaId=19190183&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "La rutina definitiva antiedad diseñada específicamente para la piel masculina. Combate los signos de fatiga y arrugas con tecnología bioactiva. Incluye 4 productos paso a paso.",
        stock: 15,
        category: 'men',
        tag: 'SET',
        rating: 5.0,
        reviewCount: 310
    },
    {
        id: 35870,
        name: "Gel de Afeitar Subzero North For Men",
        brand: "North For Men",
        price: 8.99,
        regularPrice: 13.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35870%2F35870_1.png&MediaId=19190183&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Gel de afeitado de alto rendimiento con tecnología Arctic Pro Defence y electrolitos. Proporciona un deslizamiento suave y una sensación de frescor extremo.",
        stock: 65,
        category: 'men',
        rating: 4.6,
        reviewCount: 78
    },
    // --- HTML DUMP PRODUCTS (MAQUILLAJE) ---
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 10.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png&MediaId=20570078&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Un iluminador líquido y ligero que aporta un brillo radiante y natural. Formulado con Tecnología Illuskin que refleja la luz y pigmentos perlados para un acabado luminoso. Úsalo solo o mézclalo con tu base para un glow espectacular.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 12,
        variants: {
            "Tono": [
                { value: "Luminous Gold", variationId: 471881, colorCode: "#FAD6A5" },
                { value: "Radiant Rose", variationId: 471882, colorCode: "#FFC4B4" }
            ]
        }
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 8.99,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png&MediaId=20038270&Version=4&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Descubre la perfección en un solo paso con nuestra BB Cream Beautifier MAX. Esta fórmula 10-en-1 hidrata profundamente, corrige imperfecciones, unifica el tono y protege tu piel con SPF 15. Su textura ligera se funde a la perfección para un acabado radiante y natural que dura todo el día.",
        stock: 60,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 253,
        variants: {
            "Tono": [
                { value: "Fair", variationId: 461341, colorCode: "#F3D6C6" },
                { value: "Light", variationId: 461342, colorCode: "#EBC1AC" },
                { value: "Medium", variationId: 461343, colorCode: "#D9A98E" }
            ]
        }
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 16.99,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png&MediaId=20449670&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Las icónicas perlas bronceadoras de Giordani Gold, ahora en una edición especial enriquecida con un serum antiedad. Aportan color, rubor y luminosidad con un acabado natural y juvenil gracias al ácido hialurónico.",
        stock: 40,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 8,
        variants: {
            "Tono": [
                { value: "Radiant Rose", variationId: 469011, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png" }
            ]
        }
    },
    {
        id: 46940,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 12.99,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46940%2F46940_1.png&MediaId=20026191&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Iluminador en barra cremoso y fácil de aplicar para un toque de color y luz instantáneo. Su fórmula se desliza suavemente y es perfecta para mejillas, labios y ojos.",
        stock: 55,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 522,
        variants: {
            "Tono": [
                { value: "Sparkling Rose", variationId: 469401, colorCode: "#E6A8A4" },
                { value: "Dazzling Brown", variationId: 469402, colorCode: "#C88E7B" }
            ]
        }
    },
    {
        id: 32922,
        name: "Maquillaje Liquid Silk Giordani Gold",
        brand: "Giordani Gold",
        price: 13.99,
        regularPrice: 31.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F32922%2FES%2F32922_1.png&MediaId=17437265&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Una base de maquillaje fluida y sedosa inspirada en la delicadeza de la seda. Perfecciona la tez con un acabado natural y luminoso, difuminando imperfecciones sin esfuerzo. Con SPF 12 para proteger la piel.",
        stock: 30,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1999,
        variants: {
            "Tono": [
                { value: "Vanilla", variationId: 32919, colorCode: "#F3D6C1" },
                { value: "Porcelain", variationId: 32920, colorCode: "#EADACF" },
                { value: "Light Ivory", variationId: 32921, colorCode: "#E4C8B2" },
                { value: "Natural Beige", variationId: 32922, colorCode: "#D8B9A0" }
            ]
        }
    },
    {
        id: 42113,
        name: "Crema Correctora del Color SPF 30 + Protección UVA Giordani Gold",
        brand: "Giordani Gold",
        price: 17.99,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42113%2F42113_1.png&MediaId=18141966&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "CC Cream que combina maquillaje ligero con tratamiento. Unifica el tono, corrige imperfecciones y protege contra el envejecimiento prematuro gracias a su SPF 30 y protección UVA. Para una piel radiante y protegida.",
        stock: 45,
        category: "makeup",
        rating: 4.8,
        reviewCount: 375,
        variants: {
            "Tono": [
                { value: "Light", variationId: 42113, colorCode: "#EBC1AC" },
                { value: "Medium", variationId: 42114, colorCode: "#D9A98E" }
            ]
        }
    },
    {
        id: 46332,
        name: "Maquillaje Illuskin Glow Reflective THE ONE",
        brand: "The ONE",
        price: 11.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46332%2F46332_1.png&MediaId=18706399&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Base de maquillaje con acabado glow que refleja la luz para una piel visiblemente más radiante, fresca y saludable. Su fórmula ligera proporciona una cobertura modulable y una hidratación duradera.",
        stock: 60,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.7,
        reviewCount: 585,
        variants: {
            "Tono": [
                { value: "Ivory", variationId: 46332, colorCode: "#F1D3C0" },
                { value: "Nude", variationId: 46333, colorCode: "#E3BFAC" },
                { value: "Beige", variationId: 46334, colorCode: "#D5AB91" }
            ]
        }
    },
    {
        id: 41990,
        name: "Corrector Everlasting Sync THE ONE",
        brand: "The ONE",
        price: 6.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41990%2F41990_1.png&MediaId=15045031&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Corrector de alta cobertura y larga duración que se sincroniza con tu piel para un acabado impecable y natural. Cubre ojeras e imperfecciones sin cuartearse y resiste al agua y al sudor.",
        stock: 70,
        category: "makeup",
        rating: 4.6,
        reviewCount: 1055,
        variants: {
            "Tono": [
                { value: "Light", variationId: 41990, colorCode: "#F8E2D4" },
                { value: "Medium", variationId: 41991, colorCode: "#E8C8B3" }
            ]
        }
    },
    {
        id: 44917,
        name: "Perlas con Serum Giordani Gold",
        brand: "Giordani Gold",
        price: 21.99,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44917%2F44917_1.png&MediaId=19190183&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Las perlas icónicas de Giordani Gold, ahora infusionadas con serum y ácido hialurónico para un rostro radiante, juvenil y con un toque de color natural. Perfectas como bronceador o colorete.",
        stock: 100,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1494,
        variants: {
            "Tono": [
                { value: "Luminous Peach", variationId: 44917, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44917%2F44917_1.png" },
                { value: "Golden Bronze", variationId: 44918, imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44918%2F44918_1.png" }
            ]
        }
    },
    {
        id: 42121,
        name: "Paleta de Ojos y Rostro Fabulous Beauty Giordani Gold",
        brand: "Giordani Gold",
        price: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png&MediaId=19732116&Version=5&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Una paleta de lujo todo en uno que contiene todo lo que necesitas para un look completo: sombras de ojos, coloretes, bronceador e iluminador. Pigmentos intensos y texturas sedosas.",
        stock: 25,
        category: "makeup",
        rating: 4.8,
        reviewCount: 346
    },
    {
        id: 42236,
        name: "Maquillaje Antienvejecimiento Serum Boost SPF 12 Giordani Gold",
        brand: "Giordani Gold",
        price: 31.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42236%2F42236_1.png&MediaId=18407486&Version=5&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Una base de maquillaje que es un auténtico tratamiento. Con prebióticos y extractos naturales, mejora la barrera de la piel, hidrata y proporciona una cobertura perfecta para un rostro visiblemente más joven.",
        stock: 40,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1431,
        variants: {
            "Tono": [
                { value: "Porcelain Cool", variationId: 41327, colorCode: "#F2D5C7" },
                { value: "Ivory Cool", variationId: 41328, colorCode: "#EBC4AF" },
                { value: "Beige Warm", variationId: 41330, colorCode: "#E1B696" }
            ]
        }
    },
    {
        id: 42118,
        name: "Prebase y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42118%2FES%2F42118_1.png&MediaId=17440127&Version=3&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Prebase iluminadora con perlas que se funden en la piel para crear un lienzo perfecto y radiante. Enriquecida con ácido hialurónico, hidrata, suaviza y prolonga la duración del maquillaje.",
        stock: 45,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1308
    },
    {
        id: 21339,
        name: "Solución Micelar Diamond Cellular",
        brand: "Diamond Cellular",
        price: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F21339%2FES%2F21339_1.png&MediaId=14553125&Version=6&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Lujosa solución 3 en 1: limpia, tonifica y desmaquilla. Formulada con Tecnología Micelar y el exclusivo Elixir de Diamante para una piel limpia, fresca y luminosa al instante.",
        stock: 40,
        category: "skincare",
        rating: 4.9,
        reviewCount: 1806
    },
    {
        id: 38557,
        name: "Astaxantina y Extracto de Arándano Wellosophy",
        brand: "Wellosophy",
        price: 32.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38557%2FES%2F38557_1.png&MediaId=16706466&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Potente complemento alimenticio con antioxidantes naturales. La astaxantina, procedente de microalgas, y el extracto de arándano ayudan a proteger las células del estrés oxidativo. Incluye vitaminas C y E.",
        stock: 50,
        category: "wellness",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1816
    },
    {
        id: 38556,
        name: "Omega 3 Wellosophy",
        brand: "Wellosophy",
        price: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38556%2FES%2F38556_1.png&MediaId=16654614&Version=4&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Aceite de pescado de alta calidad, procedente de fuentes sostenibles y certificado por Friend of the Sea. Rico en ácidos grasos Omega 3 (EPA y DHA) que contribuyen al funcionamiento normal del corazón, cerebro y visión.",
        stock: 60,
        category: "wellness",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 2197
    },
    {
        id: 42255,
        name: "Mascarilla Revitalizante Intensiva Acción Noche Novage+",
        brand: "Novage+",
        price: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42255%2F42255_1.png&MediaId=18501023&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Una mascarilla nocturna intensiva que nutre profundamente y reduce los signos de fatiga. Enriquecida con aceite de Inca Inchi, manteca de Cupuaçu y ácido hialurónico, para despertar con una piel descansada, suave y radiante.",
        stock: 35,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1568
    },
    {
        id: 44961,
        name: "Acondicionador Rico Reparador Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png',
        description: "Un acondicionador cremoso y nutritivo que repara y protege el cabello dañado, ayudando a reducir la rotura. Enriquecido con Queratina y Lípidos de Avena para un cabello fuerte, suave y saludable.",
        howToUse: "Después del champú, aplicar sobre el cabello húmedo de medios a puntas. Dejar actuar 1-2 minutos y aclarar con abundante agua.",
        stock: 100,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 55,
    },
    {
        id: 44960,
        name: "Acondicionador Ligero Voluminizador DUOLOGI",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44960%2F44960_1.png',
        description: "Acondicionador de textura ligera que hidrata y desenreda el cabello fino sin apelmazar. Aporta cuerpo y volumen desde la raíz para una melena con más movimiento y vitalidad.",
        howToUse: "Aplicar sobre el cabello limpio y húmedo de medios a puntas, evitando la raíz. Dejar actuar 1-2 minutos y aclarar.",
        stock: 85,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.6,
        reviewCount: 42,
    },
    {
        id: 47440,
        name: "Gel de Ducha con Fresa Orgánica Simple Joys Love Nature",
        brand: "Love Nature",
        price: 4.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47440%2F47440_1.png',
        description: "Edición Especial de verano. Un gel de ducha refrescante con un delicioso y dulce aroma a fresa orgánica. Su fórmula biodegradable limpia suavemente la piel, dejándola fresca y perfumada.",
        stock: 80,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 202,
    },
    {
        id: 46987,
        name: "Gel de Ducha con Mango Orgánico Simple Joys Love Nature",
        brand: "Love Nature",
        price: 7.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46987%2F46987_1.png',
        description: "Disfruta de una ducha tropical con este gel formulado con extracto de mango orgánico. Su aroma jugoso y exótico te transportará, mientras su fórmula suave y biodegradable cuida tu piel.",
        stock: 75,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 731,
    },
    {
        id: 47009,
        name: "Gel de Ducha con Aloe Vera Orgánico Simple Joys Love Nature",
        brand: "Love Nature",
        price: 7.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47009%2F47009_1.png',
        description: "Un gel de ducha hidratante y calmante enriquecido con Aloe Vera orgánico, conocido por sus propiedades suavizantes. Ideal para una limpieza refrescante que deja la piel confortable.",
        stock: 60,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 717,
    },
    {
        id: 46642,
        name: "Jabón Líquido Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense&Co.",
        price: 11.99,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png',
        description: "Un elegante jabón líquido para manos y cuerpo con aceites esenciales naturales de limón y verbena. Su fórmula hidratante y su vibrante aroma cítrico convierten la limpieza diaria en un ritual de lujo.",
        stock: 30,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 1139,
    },
    {
        id: 46643,
        name: "Loción Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense&Co.",
        price: 12.99,
        regularPrice: 22.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46643%2F46643_1.png',
        description: "Loción hidratante para manos y cuerpo enriquecida con aceites esenciales naturales de limón y verbena. Deja la piel suave, flexible y con un aroma refrescante y revitalizante.",
        stock: 40,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 856,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica y duradera. Con notas de Grosella Negra, la flor de Datura y Sándalo. Un aroma sensual y misterioso, perfecto para la noche.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 46968,
        name: "Crema para Manos y Cuerpo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 18.00,
        regularPrice: 24.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png',
        description: "La legendaria crema nutritiva con extractos de origen orgánico de leche y miel. Hidrata intensamente manos y cuerpo, dejando la piel suave, flexible y delicadamente perfumada con su icónico aroma.",
        stock: 80,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 3560,
    },
    {
        id: 36151,
        name: "Crema Universal con Aceite de Grosella Negra",
        brand: "Tender Care",
        price: 7.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36151%2F36151_1.png',
        description: "El bálsamo clásico y multiusos de Oriflame, ahora con un delicioso y afrutado toque de aceite de semilla de grosella negra. Nutre, suaviza y protege las zonas secas como labios, codos, cutículas y talones.",
        stock: 100,
        category: 'skincare',
        rating: 4.9,
        reviewCount: 2226,
    },
    {
        id: 47677,
        name: "Cepillo Estilizador Glam On-the-Go",
        brand: "StylerPRO",
        price: 64.99,
        regularPrice: 80.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47677%2F47677_1.png",
        description: "Cepillo alisador compacto, inalámbrico y recargable por USB. Ideal para retocar tu peinado en cualquier lugar y momento. Calentamiento rápido y placas de cerámica para un acabado suave y brillante.",
        stock: 15,
        category: 'hair',
        tag: 'NOVEDAD',
        rating: 4.7,
        reviewCount: 70,
    },
    {
        id: 47878,
        name: "Esponja de Baño Lather Lily",
        brand: "Love Nature",
        price: 7.49,
        regularPrice: 9.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47878%2F47878_1.png",
        description: "Esponja de baño suave y texturizada que genera abundante espuma para una ducha placentera y una limpieza eficaz. Ayuda a exfoliar suavemente la piel.",
        stock: 50,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.6,
        reviewCount: 209,
    },
    {
        id: 47202,
        name: "Crema de Manos y Uñas Protectora con Fruta de la Pasión",
        brand: "Love Nature",
        price: 4.99,
        regularPrice: 11.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47202%2F47202_1.png',
        description: "Protege e hidrata tus manos y uñas con esta crema de rápida absorción y un exótico y jugoso aroma a fruta de la pasión. Perfecta para llevar en el bolso.",
        stock: 65,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 713,
    },
    // --- NUEVAS OFERTAS SEMANA 2 ---
    {
        id: 38883,
        name: "Bálsamo de Labios LipSpa THE ONE - Rose",
        brand: "The ONE",
        price: 6.99,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38883%2F38883_1.png",
        description: "Bálsamo labial de doble núcleo que hidrata y protege los labios con un toque de color. Con Tecnología Dual Core para una hidratación intensa y duradera.",
        stock: 100,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 450
    },
    {
        id: 42785,
        name: "Eau de Toilette Lucia",
        brand: "Oriflame",
        price: 18.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42785%2F42785_1.png",
        description: "Una fragancia luminosa y femenina que celebra la luz. Con notas de Lirio Blanco, Hiedra y Sándalo. Un clásico atemporal de Oriflame.",
        stock: 50,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1200
    },
    {
        id: 40809,
        name: "Eau de Parfum Whispers of Me",
        brand: "Oriflame",
        price: 19.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40809%2F40809_1.png",
        description: "Una fragancia íntima y sensual que susurra elegancia. Notas florales y amaderadas que se funden con tu piel.",
        stock: 45,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 85
    },
    {
        id: 42520,
        name: "Eau de Toilette Lucia Bright Aura",
        brand: "Oriflame",
        price: 18.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42520%2F42520_1.png",
        description: "Una versión vibrante y fresca de Lucia. Con notas de Grosella Blanca, Flor de Olivo y Ámbar. Irradia energía y luz.",
        stock: 40,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 340
    },
    {
        id: 42495,
        name: "Eau de Parfum Amber Elixir",
        brand: "Oriflame",
        price: 19.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42495%2F42495_1.png",
        description: "Inspirada en la calidez y el misterio del ámbar. Una fragancia oriental con notas de Mandarina, Heliotropo y Ámbar. Sensual y envolvente.",
        stock: 60,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 2100
    },
    {
        id: 42864,
        name: "Eau de Toilette Eclat Homme",
        brand: "Oriflame",
        price: 22.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42864%2F42864_1.png",
        description: "La esencia de la elegancia francesa para el hombre. Una fragancia sofisticada con notas de Cidra, Té del Himalaya y Cuero Barenia.",
        stock: 55,
        category: "men",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1500
    },
    {
        id: 38527,
        name: "Eau de Parfum Ascendant Intense",
        brand: "Oriflame",
        price: 19.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38527%2F38527_1.png",
        description: "Una fragancia poderosa y masculina que irradia fuerza. Con notas orientales y especiadas.",
        stock: 40,
        category: "men",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 280
    },
    {
        id: 45357,
        name: "Eau de Parfum Possess Absolute Man",
        brand: "Oriflame",
        price: 28.99,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45357%2F45357_1.png",
        description: "Una fragancia audaz y carismática para el hombre que lo posee todo. Notas intensas de Pimienta Negra y Canela.",
        stock: 30,
        category: "men",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 150
    },
    {
        id: 45967,
        name: "Eau de Parfum Essenza Man Elixir",
        brand: "Giordani Gold",
        price: 38.99,
        regularPrice: 65.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45967%2F45967_1.png",
        description: "La máxima expresión del lujo masculino. Una fragancia intensa y duradera con el exclusivo acorde Essenza.",
        stock: 25,
        category: "men",
        tag: "OFERTA",
        rating: 5.0,
        reviewCount: 95
    },
    {
        id: 44968,
        name: "Tratamiento CC Hair Beautifier Duologi",
        brand: "DUOLOGI",
        price: 8.49,
        regularPrice: 15.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44968%2F44968_1.png",
        description: "Tratamiento capilar multibeneficios en spray. Hidrata, protege, suaviza y aporta brillo al cabello en un solo paso.",
        stock: 70,
        category: "hair",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 320
    },
    {
        id: 46982,
        name: "Spray Antitranspirante para Pies Feet Up Expert",
        brand: "Feet Up",
        price: 8.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46982%2F46982_1.png",
        description: "Control de olor 48h para pies frescos y secos. Tecnología Pro-Resist para una protección avanzada.",
        stock: 85,
        category: "personal-care",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 410
    },
    {
        id: 13659,
        name: "Crema de Día de Diamond Cellular",
        brand: "Diamond Cellular",
        price: 25.99,
        regularPrice: 59.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2F13659_1.png",
        description: "Crema de día antiedad de lujo que aporta luminosidad y firmeza a la piel. Con Elixir de Diamante.",
        stock: 40,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1560
    },
    // --- PREMIOS ESPECIALES ---
    {
        id: 150838,
        name: "Mascarilla Revitalizante Intensiva Novage+",
        brand: "Novage+",
        price: 3.00,
        regularPrice: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F150838%2F150838_1.png",
        description: "Mascarilla nocturna intensiva que nutre profundamente y reduce los signos de fatiga.",
        stock: 20,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 500
    },
    {
        id: 41039,
        name: "Serum Blemish + Age Defy Novage+",
        brand: "Novage+",
        price: 3.00,
        regularPrice: 60.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41039%2F41039_1.png",
        description: "Serum avanzado que combate las imperfecciones y los signos de la edad simultáneamente.",
        stock: 15,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 120
    },
    {
        id: 46792,
        name: "Eau de Toilette Eclat Femme Weekend Riviera",
        brand: "Oriflame",
        price: 3.00,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46792%2F46792_1.png",
        description: "Una fragancia floral y afrutada que evoca la brisa de la Riviera francesa.",
        stock: 25,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 80
    },
    {
        id: 46795,
        name: "Eau de Toilette Eclat Homme Weekend Azur",
        brand: "Oriflame",
        price: 3.00,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46795%2F46795_1.png",
        description: "Fragancia masculina fresca y sofisticada, perfecta para el fin de semana.",
        stock: 20,
        category: "men",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 65
    },
    {
        id: 47514,
        name: "Eau de Parfum Miss Giordani Floral",
        brand: "Giordani Gold",
        price: 3.00,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47514%2F47514_1.png",
        description: "Una fragancia floral luminosa que celebra la feminidad y la alegría.",
        stock: 30,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 110
    }
];
